"attribute" = "orange_6"

"type" = "teal_4"
"type.builtin" = "teal_4"

"constructor" = "blue_4"

"constant" = "violet_4"
"constant.builtin" = { fg = "violet_4", modifiers = ["bold"] }
"constant.character" = "teal_5"
"constant.numeric" = { fg = "teal_5", modifiers = ["bold"] }
"constant.character.escape" = "violet_4"

"string" = "teal_3"
"string.regexp" = "purple_4"
"string.special" = "blue_4"

"comment" = "light_6"

"variable" = "dark_5"
"variable.parameter" = "orange_4"
"variable.builtin" = "orange_4"
"variable.other" = "teal_4"
"variable.other.member" = "teal_5"

"label" = "purple_4"

"punctuation" = "dark_4"
"punctuation.delimiter" = "dark_4"
"punctuation.bracket" = "dark_4"
"punctuation.special" = "red_5"

"keyword" = { fg = "orange_4", modifiers = ["bold"] }
"keyword.control" = { fg = "orange_4", modifiers = ["bold"] }
"keyword.operator" = "purple_4"
"keyword.directive" = { fg = "orange_4", modifiers = ["bold"] }
"keyword.function" = "orange_4"
"keyword.storage" = { fg = "orange_4", modifiers = ["bold"] }

"operator" = "purple_4"

"function" = "blue_4"
"function.builtin" = "blue_4"
"function.macro" = { fg = "blue_4", modifiers = ["bold"] }
"function.special" = { fg = "blue_4", modifiers = ["bold"] }

"tag" = "teal_4"

"namespace" = "orange_4"

"markup" = "dark_4"
"markup.heading" = { fg = "teal_4", modifiers = ["bold"] }
"markup.list" = { fg = "orange_4", modifiers = ["bold"] }
"markup.bold" = { fg = "dark_4", modifiers = ["bold"] }
"markup.italic" = { fg = "dark_4", modifiers = ["italic"] }
"markup.link" = { fg = "blue_5", modifiers = ["underlined"] }
"markup.quote" = { fg = "dark_3", modifiers = ["italic"] }
"diff.plus" = "teal_5"
"diff.minus" = "red_3"
"diff.delta" = "orange_5"
"diff.delta.moved" = "orange_4"

"ui.background" = { fg = "dark_4", bg = "light_1" }
"ui.background.separator" = { fg = "split_and_borders", bg = "light_2" }
"ui.cursor" = { fg = "light_2", bg = "dark_5" }
"ui.cursor.insert" = { fg = "light_2", bg = "dark_5" }
"ui.cursor.primary.insert" = { fg = "light_2", bg = "dark_5" }
"ui.cursor.select" = { fg = "light_2", bg = "dark_5" }
"ui.cursor.match" = { fg = "light_2", bg = "blue_1" }
"ui.cursor.primary" = { fg = "light_2", bg = "dark_6" }
"ui.linenr" = "light_5"
"ui.linenr.selected" = { fg = "dark_2", bg = "light_3", modifiers = [
  "bold",
] }
"ui.statusline" = { fg = "dark_4", bg = "light_4" }
"ui.statusline.inactive" = { fg = "dark_3", bg = "light_3" }
"ui.statusline.insert" = { fg = "light_5", bg = "teal_3" }
"ui.statusline.select" = { fg = "light_4", bg = "blue_3" }
"ui.popup" = { bg = "light_3" }
"ui.window" = "split_and_borders"
"ui.help" = { bg = "light_3" }
"ui.text" = "dark_4"
"ui.virtual" = "light_1"
"ui.virtual.ruler" = { bg = "light_5"}
"ui.menu" = { fg = "dark_4", bg = "light_3" }
"ui.menu.selected" = { fg = "dark_4", bg = "blue_1" }
"ui.menu.scroll" = { fg = "dark_6", bg = "light_3" }
"ui.selection" = { bg = "blue_0" }
"ui.selection.primary" = { bg = "blue_0" }
"ui.cursorline.primary" = { bg = "light_3" }
"ui.virtual.whitespace" = "light_7"

"warning" = "yellow_4"
"error" = "red_5"
"info" = "purple_3"
"hint" = "blue_3"

"diagnostic.hint" = { fg = "blue_4", modifiers = ["dim"] }
"diagnostic.info" = { fg = "purple_4", modifiers = ["dim"] }
"diagnostic.error" = { fg = "red_5", modifiers = ["underlined"] }
"diagnostic.warning" = { fg = "yellow_4", modifiers = ["underlined"] }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"ui.bufferline" = { fg = "light_7", bg = "light_2" }
"ui.bufferline.active" = { fg = "dark_4", bg = "light_4", modifiers = ["bold"]}

[palette]
blue_0 = "#d3e4f9"
blue_1 = "#99C1F1"
blue_2 = "#62A0EA"
blue_3 = "#3584E4"
blue_4 = "#1C71D8"
blue_5 = "#1A5FB4"
blue_6 = "#1B497E"
blue_7 = "#193D66"
brown_1 = "#CDAB8F"
brown_2 = "#B5835A"
brown_3 = "#986A44"
brown_4 = "#865E3C"
brown_5 = "#63452C"
chameleon_3 = "#4E9A06"
dark_1 = "#77767B"
dark_2 = "#5E5C64"
dark_3 = "#504E55"
dark_4 = "#3D3846"
dark_5 = "#241F31"
dark_6 = "#000000"
green_1 = "#8FF0A4"
green_2 = "#57E389"
green_3 = "#33D17A"
green_4 = "#2EC27E"
green_5 = "#26A269"
green_6 = "#1F7F56"
green_7 = "#1C6849"
light_1 = "#FFFFFF"
light_2 = "#FCFCFC"
light_3 = "#F6F5F4"
light_4 = "#DEDDDA"
light_5 = "#C0BFBC"
light_6 = "#B0AFAC"
light_7 = "#9A9996"
orange_1 = "#FFBE6F"
orange_2 = "#FFA348"
orange_3 = "#FF7800"
orange_4 = "#E66100"
orange_5 = "#C64600"
purple_1 = "#DC8ADD"
purple_2 = "#C061CB"
purple_3 = "#9141AC"
purple_4 = "#813D9C"
purple_5 = "#613583"
red_1 = "#F66151"
red_2 = "#ED333B"
red_3 = "#E01B24"
red_4 = "#C01C28"
red_5 = "#A51D2D"
teal_1 = "#93DDC2"
teal_2 = "#5BC8AF"
teal_3 = "#33B2A4"
teal_4 = "#26A1A2"
teal_5 = "#218787"
violet_2 = "#7D8AC7"
violet_3 = "#6362C8"
violet_4 = "#4E57BA"
yellow_1 = "#F9F06B"
yellow_2 = "#F8E45C"
yellow_3 = "#F6D32D"
yellow_4 = "#F5C211"
yellow_5 = "#E5A50A"
yellow_6 = "#D38B09"
